#!/usr/bin/env python3
"""Extract repeatable firmware chunks for static analysis tools."""

from __future__ import annotations

import hashlib
import json
import zlib
from dataclasses import asdict, dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SYSTEM_IMAGE = ROOT / "opt" / "TurboSystem_sw" / "51.80.300.021" / "image.bin"
OUT_DIR = ROOT / "analysis" / "extracted"

STREAM_OFFSETS = [0x24BBB5, 0x676129, 0x67753B, 0x677D67, 0x132314C]
MINIBOOT_START = 0x21D5D8
MINIBOOT_END = 0x24BBB5
MINIBOOT_BASE = 0x03800000


@dataclass
class ExtractedItem:
    name: str
    path: str
    source_offset: int
    size: int
    load_base: int | None
    sha256: str
    note: str


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def write_item(
    items: list[ExtractedItem],
    name: str,
    data: bytes,
    source_offset: int,
    load_base: int | None,
    note: str,
) -> None:
    path = OUT_DIR / name
    path.write_bytes(data)
    items.append(
        ExtractedItem(
            name=name,
            path=str(path.relative_to(ROOT)),
            source_offset=source_offset,
            size=len(data),
            load_base=load_base,
            sha256=sha256(data),
            note=note,
        )
    )


def decompress_stream(system_data: bytes, offset: int) -> tuple[bytes, int]:
    obj = zlib.decompressobj()
    payload = obj.decompress(system_data[offset:])
    if not obj.eof:
        raise RuntimeError(f"zlib stream at 0x{offset:x} did not reach EOF")
    consumed = len(system_data) - offset - len(obj.unused_data)
    return payload, consumed


def render_markdown(items: list[ExtractedItem]) -> str:
    lines = [
        "# Extracted Analysis Inputs",
        "",
        "Generated by `tools/extract_analysis_inputs.py` from the active stock-parity system image.",
        "",
        "| Name | Source offset | Size | Load base | SHA256 | Note |",
        "| --- | ---: | ---: | ---: | --- | --- |",
    ]
    for item in items:
        base = "n/a" if item.load_base is None else f"`0x{item.load_base:x}`"
        lines.append(
            f"| `{item.path}` | `0x{item.source_offset:x}` | `0x{item.size:x}` | "
            f"{base} | `{item.sha256}` | {item.note} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    system_data = SYSTEM_IMAGE.read_bytes()
    items: list[ExtractedItem] = []

    write_item(
        items,
        "system_miniboot_region_0x21d5d8_armle.bin",
        system_data[MINIBOOT_START:MINIBOOT_END],
        MINIBOOT_START,
        MINIBOOT_BASE,
        "ARM little-endian mini-boot/check region; outer offset maps to runtime 0x03800000.",
    )

    for index, offset in enumerate(STREAM_OFFSETS, 1):
        payload, consumed = decompress_stream(system_data, offset)
        write_item(
            items,
            f"system_stream{index}_0x{offset:x}_inflated.bin",
            payload,
            offset,
            0 if index == 1 else None,
            f"Inflated zlib stream; compressed length 0x{consumed:x}.",
        )

    manifest = {"items": [asdict(item) for item in items]}
    (OUT_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="ascii")
    (OUT_DIR / "README.md").write_text(render_markdown(items), encoding="ascii")
    print(f"wrote {OUT_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
